---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fio
  labels:
    app: fio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fio
  template:
    metadata:
      labels:
        app: fio
    spec:
      containers:
      - name: fio
        image: xridge/fio:3.13
        args: ["--filename=/scratch/pvc --iodepth=1 --rw=randwrite --bs=4m"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: fio-data
          mountPath: /scratch
      restartPolicy: Always
      volumes:
      - name: fio-data
        persistentVolumeClaim:
          claimName: fio-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-claim
spec:
  storageClassName: nutanix-volume
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi