apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: elastic-grafanadatasource
  namespace: grafana
spec:
  datasources:
    - jsonData:
        tlsSkipVerify: true
      editable: true
      name: kube-burner
      type: elasticsearch
      url: '${esRoute}'
      basicAuthPassword: '${esPassword}'
      basicAuth: true
      basicAuthUser: elastic
  name: elastic-grafanadatasource.yaml