apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
spec:
  config:
    security:
      admin_password: ${GRAFANA_PASSWORD}
      admin_user: root
    auth.basic:
      enabled: true
    auth:
      disable_signout_menu: true
  ingress:
    enabled: true