apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
spec:
  dashboardLabelSelector:
    - matchExpressions:
        - { key: app, operator: In, values: [grafana] }
  config:
    security:
      admin_password: ${GRAFANA_PASSWORD}
      admin_user: root
    auth.anonymous:
      enabled: true
    auth.basic:
      enabled: true
    auth:
      disable_signout_menu: true
  ingress:
    enabled: true
