{
 "title": "Kube-burner report v2",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource1", "label": "Datasource", "query": "elasticsearch" },
   {
    "name": "platform",
    "label": "Platform",
    "query": "{\"find\": \"terms\", \"field\": \"platform.keyword\"}"
   },
   {
    "name": "sdn",
    "label": "SDN type",
    "query": "{\"find\": \"terms\", \"field\": \"sdn_type.keyword\"}"
   },
   {
    "name": "workload",
    "label": "Workload",
    "query": "{\"find\": \"terms\", \"field\": \"workload.keyword\", \"query\": \"platform.keyword: $platform AND sdn_type.keyword: $sdn\"}"
   },
   {
    "name": "worker_count",
    "label": "Worker count",
    "query": "{\"find\": \"terms\", \"field\": \"worker_nodes_count\", \"query\": \"platform.keyword: $platform AND sdn_type.keyword: $sdn AND workload.keyword: $workload\"}"
   },
   {
    "name": "uuid",
    "label": "UUID",
    "query": "{\"find\": \"terms\", \"field\": \"uuid.keyword\", \"query\": \"platform.keyword: $platform AND sdn_type.keyword: $sdn AND workload.keyword: $workload AND worker_nodes_count: $worker_count\"}"
   },
   {
    "name": "master",
    "label": "Master nodes",
    "query": "{ \"find\" : \"terms\", \"field\": \"labels.node.keyword\", \"query\": \"metricName.keyword: nodeRoles AND labels.role.keyword: master AND uuid.keyword: $uuid\"}"
   },
   {
    "name": "worker",
    "label": "Worker nodes",
    "query": "{ \"find\" : \"terms\", \"field\": \"labels.node.keyword\", \"query\": \"metricName.keyword: nodeRoles AND labels.role.keyword: worker AND uuid.keyword: $uuid\"}"
   },
   {
    "name": "infra",
    "label": "Infra nodes",
    "query": "{ \"find\" : \"terms\", \"field\": \"labels.node.keyword\",  \"query\": \"metricName.keyword: nodeRoles AND labels.role.keyword: infra AND uuid.keyword: $uuid\"}"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "{ \"find\" : \"terms\", \"field\": \"labels.namespace.keyword\", \"query\": \"labels.namespace.keyword: /openshift-.*/ AND uuid.keyword: $uuid\"}"
   },
   { "name": "latencyPercentile", "label": "Latency percentile", "query": "P99, P95, P50" }
  ]
 },
 "panels": [
  {
   "title": "Node count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.role.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "coun",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"nodeRoles\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Namespaces",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"namespaceCount\" AND labels.phase: \"Active\"",
     "timeField": "timestamp"
    },
    {
     "alias": "Services",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"serviceCount\"",
     "timeField": "timestamp"
    },
    {
     "alias": "Services",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"deploymentCount\"",
     "timeField": "timestamp"
    },
    {
     "alias": "Services",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"secretCount\"",
     "timeField": "timestamp"
    },
    {
     "alias": "ConfigMaps",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"configmapCount\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "OpenShift version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": null,
       "settings": { "interval": "1s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"clusterVersion\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Etcd version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": null,
       "settings": { "interval": "1s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"etcdVersion\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "table-old",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": null,
       "settings": { "interval": "1s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"jobSummary\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "table-old",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": null,
       "settings": { "interval": "1s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "uuid.keyword: $uuid AND result.keyword: *",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Cluster status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Masters CPU utilization",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "{{labels.instance.keyword}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "labels.instance.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "settings": { "script": "_value * 100" }, "type": "sum" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeCPU-Masters\" AND NOT labels.mode.keyword: idle AND NOT labels.mode.keyword: steal",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Masters Memory utilization",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Available {{labels.instance.keyword}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "labels.instance.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "value",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeMemoryAvailable-Masters\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Node Status Summary",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{labels.condition.keyword}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "labels.condition.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "value",
         "id": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeStatus\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Pod Status Summary",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{labels.phase.keyword}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "labels.phase.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "value",
         "id": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"podStatusCount\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Kube-apiserver CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "{{labels.namespace.keyword}}-{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "value",
         "id": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.container.keyword: kube-apiserver",
       "timeField": "timestamp"
      },
      {
       "alias": "{{labels.namespace.keyword}}-{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "value",
         "id": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerCPU-Masters\" AND labels.container.keyword: kube-apiserver",
       "timeField": "timestamp"
      },
      {
       "alias": "Avg CPU {{labels.container.keyword}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "value",
         "id": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.container.keyword: kube-apiserver",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Kube-apiserver Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Rss {{labels.namespace.keyword}}-{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "value",
         "id": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.container.keyword: kube-apiserver",
       "timeField": "timestamp"
      },
      {
       "alias": "Rss {{labels.namespace.keyword}}-{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "value",
         "id": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerMemory-Masters\" AND labels.container.keyword: kube-apiserver",
       "timeField": "timestamp"
      },
      {
       "alias": "Avg Rss {{labels.container.keyword}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "value",
         "id": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.container.keyword: kube-apiserver",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Active Kube-controller-manager CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "{{labels.namespace.keyword}}-{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "value",
         "id": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.container.keyword: kube-controller-manager",
       "timeField": "timestamp"
      },
      {
       "alias": "{{labels.container.keyword}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "value",
         "id": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerCPU-Masters\" AND labels.container.keyword: kube-controller-manager",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Active Kube-controller-manager memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "{{labels.namespace.keyword}}-{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "value",
         "id": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.container.keyword: kube-controller-manager",
       "timeField": "timestamp"
      },
      {
       "alias": "{{labels.container.keyword}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "value",
         "id": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerMemory-Masters\" AND labels.container.keyword: kube-controller-manager",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Kube-scheduler CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "{{labels.namespace.keyword}}-{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "value",
         "id": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.container.keyword: kube-scheduler",
       "timeField": "timestamp"
      },
      {
       "alias": "{{labels.container.keyword}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "value",
         "id": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerCPU-Masters\" AND labels.container.keyword: kube-scheduler",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Kube-scheduler memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "{{labels.namespace.keyword}}-{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "value",
         "id": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.container.keyword: kube-scheduler",
       "timeField": "timestamp"
      },
      {
       "alias": "Rss {{labels.container.keyword}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "value",
         "id": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerMemory-Masters\" AND labels.container.keyword: kube-scheduler",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Hypershift Controlplane CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "labels.pod.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
         "type": "terms"
        },
        {
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "4",
         "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "value",
         "id": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerCPU-Controlplane\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Hypershift Controlplane RSS memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "labels.pod.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
         "type": "terms"
        },
        {
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "4",
         "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "value",
         "id": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerMemory-Controlplane\"",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  { "title": "Pod latency stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Average pod latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{field}}",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "podReadyLatency",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "schedulingLatency",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "initializedLatency",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: podLatencyMeasurement",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Pod latencies summary $latencyPercentile",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$latencyPercentile {{term quantileName.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "quantileName.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "$latencyPercentile",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: podLatencyQuantilesMeasurement",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Pod conditions latency",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "namespace.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "5", "size": "100" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "nodeName.keyword",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "100" },
       "type": "terms"
      },
      {
       "field": "podName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "5", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "schedulingLatency",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "initializedLatency",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "containersReadyLatency",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "podReadyLatency",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: podLatencyMeasurement",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top 10 Container runtime network setup latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "alias": "{{labels.node.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.node.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: containerNetworkSetupLatency",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Scheduling throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: schedulingThroughput",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "OVNKubernetes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "ovnkube-master CPU usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "labels.pod.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.container.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "3",
         "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.pod.keyword: /ovnkube-master.*/",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "ovnkube-master Memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "field": "labels.pod.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "3",
         "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "sum" }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.pod.keyword: /ovnkube-master.*/",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "ovn-controller CPU usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "labels.pod.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "3",
         "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.namespace.keyword: \"openshift-ovn-kubernetes\"  AND labels.pod.keyword: /ovnkube-node.*/ AND labels.container.keyword: \"ovn-controller\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "ovn-controller Memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "field": "labels.pod.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "3",
         "settings": { "interval": "30s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "sum" }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.namespace.keyword: \"openshift-ovn-kubernetes\"  AND labels.pod.keyword: /ovnkube-node.*/ AND labels.container.keyword: \"ovn-controller\"",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  { "title": "etcd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "etcd 99th disk WAL fsync latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"99thEtcdDiskWalFsyncDurationSeconds\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "etcd 99th disk backend commit latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"99thEtcdDiskBackendCommitDurationSeconds\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Etcd leader changes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Etcd leader changes",
     "bucketAggs": [
      { "field": "timestamp", "id": "1", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid: $uuid AND metricName.keyword: etcdLeaderChangesRate",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Etcd 99th network peer roundtrip time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.pod.keyword}} to {{labels.To.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.To.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: 99thEtcdRoundTripTimeSeconds",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Etcd CPU utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{labels.namespace.keyword}}-{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "labels.namespace.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.container.keyword: etcd",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Etcd memory utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{labels.namespace.keyword}}-{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "labels.namespace.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.container.keyword: etcd",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "API and Kubeproxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Read Only API request P99 latency - resource scoped",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.verb.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "labels.resource.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: readOnlyAPICallsLatency AND labels.scope.keyword: resource",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Read Only API request P99 latency - namespace scoped",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.verb.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: readOnlyAPICallsLatency AND labels.scope.keyword: namespace",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Read Only API request P99 latency - cluster scoped",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.verb.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: readOnlyAPICallsLatency AND labels.scope.keyword: cluster",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Mutating API request P99 latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.verb.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: mutatingAPICallsLatency",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "API request rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.verb.keyword}} {{labels.resource.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.resource.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.verb.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: APIRequestRate",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Service sync latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Latency",
     "bucketAggs": [
      {
       "field": "labels.instance.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid: $uuid AND metricName.keyword: kubeproxyP99ProgrammingLatency",
     "timeField": "timestamp"
    },
    {
     "alias": "Latency",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid: $uuid AND metricName.keyword: serviceSyncLatency",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Cluster Kubelet & CRI-O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Kubelet process CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.node.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: kubeletCPU",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Kubelet process RSS memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.node.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: kubeletMemory",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CRI-O process CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.node.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: crioCPU",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CRI-O RSS memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.node.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: crioMemory",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Master: $master", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 }, "repeat": "$master" },
  {
   "title": "Container CPU usage $master",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{labels.pod.keyword}} {{labels.container.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.node.keyword: $master AND labels.namespace.keyword: $namespace",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Container RSS memory $master",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{labels.pod.keyword}} {{labels.container.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.node.keyword: $master AND labels.namespace.keyword: $namespace",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CPU $master",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{labels.mode.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.mode.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "settings": { "script": { "inline": "_value*100" } }, "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeCPU-Masters\" AND labels.instance.keyword: $master",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Memory $master",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Available",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeMemoryAvailable-Masters\" AND labels.instance.keyword: $master",
     "timeField": "timestamp"
    },
    {
     "alias": "Total",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeMemoryTotal-Masters\" AND labels.instance.keyword: $master",
     "timeField": "timestamp"
    },
    {
     "alias": "Utilization",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeMemoryUtilization-Masters\" AND labels.instance.keyword: $master",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Worker: $worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 }, "repeat": "$worker" },
  {
   "title": "Container CPU usage $worker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{labels.pod.keyword}} {{labels.container.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.node.keyword: $worker AND labels.namespace.keyword: $namespace",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Container RSS memory $worker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 130 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{labels.pod.keyword}} {{labels.container.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.node.keyword: $worker AND labels.namespace.keyword: $namespace",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CPU $worker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{labels.mode.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.mode.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "settings": { "script": { "inline": "_value*100" } }, "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeCPU-Workers\" AND labels.instance.keyword: $worker",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Memory $worker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 139 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Available",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeMemoryAvailable-Workers\" AND labels.instance.keyword: $worker",
     "timeField": "timestamp"
    },
    {
     "alias": "Total",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeMemoryTotal-Workers\" AND labels.instance.keyword: $worker",
     "timeField": "timestamp"
    },
    {
     "alias": "Utilization",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeMemoryUtilization-Workers\" AND labels.instance.keyword: $worker",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Infra: $infra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 148 }, "repeat": "$infra" },
  {
   "title": "Container CPU usage $infra",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 149 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{labels.pod.keyword}} {{labels.container.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.node.keyword: $infra AND labels.namespace.keyword: $namespace",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Container RSS memory $infra",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 149 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{labels.pod.keyword}} {{labels.container.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.node.keyword: $infra AND labels.namespace.keyword: $namespace",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CPU $infra",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 158 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{labels.mode.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.mode.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "settings": { "script": { "inline": "_value*100" } }, "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeCPU-Infra\" AND labels.instance.keyword: $infra",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Memory $infra",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 158 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Available",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeMemoryAvailable-Infra\" AND labels.instance.keyword: $infra",
     "timeField": "timestamp"
    },
    {
     "alias": "Total",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeMemoryTotal-Infra\" AND labels.instance.keyword: $infra",
     "timeField": "timestamp"
    },
    {
     "alias": "Utilization",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeMemoryUtilization-Infra\" AND labels.instance.keyword: $infra",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Aggregated worker nodes usage (only in aggregated metrics profile)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 167 }
  },
  {
   "title": "Avg CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 168 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{labels.mode.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.mode.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "settings": { "script": { "inline": "_value*100" } }, "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeCPU-AggregatedWorkers\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Avg Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 168 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Available",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeMemoryAvailable-AggregatedWorkers\"",
     "timeField": "timestamp"
    },
    {
     "alias": "Total",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeMemoryTotal-AggregatedWorkers\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 177 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}: {{labels.container.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerCPU-AggregatedWorkers\" AND labels.namespace.keyword: $namespace",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Container memory RSS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 177 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}: {{labels.container.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerMemory-AggregatedWorkers\" AND labels.namespace.keyword: $namespace",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}