apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: set-max-pods 
spec:
  machineConfigPoolSelector:
    matchLabels:
      custom-kubelet: large-pods 
  kubeletConfig:
    podsPerCore: 0
    maxPods: 450
