global:
  writeToFile: false
  createTarball: false
  indexerConfig:
    enabled: true
    esServers: [https://elastic:{{ .esPassword }}@{{ .esRoute }}]
    insecureSkipVerify: true
    defaultIndex: kube-burner
    type: elastic
  measurements:
    - name: podLatency
      esIndex: kube-burner

jobs:
  - name: kubelet-density-heavy
    jobIterations: {{ .JOB_ITERATIONS}}
    qps: {{ .QPS}}
    burst: {{ .QPS}}
    namespacedIterations: true
    namespace: kubelet-density-heavy
    waitWhenFinished: true
    jobPause: 120s
    podWait: false
    objects:

      - objectTemplate: templates/postgres-deployment.yml
        replicas: 1

      - objectTemplate: templates/app-deployment.yml
        replicas: 1
        inputVars:
          readinessPeriod: 10

      - objectTemplate: templates/postgres-service.yml
        replicas: 1
