kind: Deployment
apiVersion: apps/v1
metadata:
  name: perfapp-{{.Replica}}-{{.Iteration}}
spec:
  template:
    metadata:
      labels:
        name: perfapp-{{.Replica}}-{{.Iteration}}
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
      - name: perfapp
        image: xridge/pgbench:latest
        args: ["HOSTNAME", "KUBERNETES_PORT"]
        resources:
          requests:
            cpu: 2m
            memory: 6Mi
        env:
        - name: POSTGRESQL_USER
          value: admin
        - name: POSTGRESQL_PASSWORD
          value: secret
        - name: POSTGRESQL_DATABASE
          value: kubelet-density
        - name: POSTGRESQL_HOSTNAME
          value: postgresql-{{.Replica}}-{{.Iteration}}
        - name: POSTGRESQL_PORT
          value: '5432'
        - name: POSTGRESQL_RETRY_INTERVAL
          value: '5'
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
      restartPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      name: perfapp-{{.Replica}}-{{.Iteration}}
  triggers:
  - type: ConfigChange
  strategy:
    type: RollingUpdate
