apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: postgres-{{.Replica}}-{{.Iteration}}
  name: postgres-pvc-{{.Replica}}-{{.Iteration}}
spec:
  storageClassName: nutanix-volume
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M
