apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: postgres-pvc-{{.Replica}}-{{.Iteration}}-snapshot
spec:
  source:
    persistentVolumeClaimName: postgres-pvc-{{.Replica}}-{{.Iteration}}
  volumeSnapshotClassName: nutanix-snapshot-class

