apiVersion: v1
kind: Pod
metadata:
  name: command-demo2
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container2
    image: xridge/pgbench
    args: ["-h","postgresql-1-993","-p","5432","-i","-c","2","-j","2","-T","60","kubelet-density","-U","admin"]
    env:
    - name: PGPASSWORD
      value: secret
  restartPolicy: Always

